"""Generates the config.py consumed by the mtprotoproxy engine
(github.com/alexbers/mtprotoproxy). One config file per proxy instance."""
from __future__ import annotations


def render_config(port: int, secret: str, tls_domain: str, ad_tag: str | None = None) -> str:
    lines = [
        "# Auto-generated by MTProto Panel. Do not edit by hand.",
        f"PORT = {int(port)}",
        f'USERS = {{"panel": "{secret}"}}',
        # FakeTLS only: traffic looks like a genuine TLS session to TLS_DOMAIN.
        'MODES = {"classic": False, "secure": False, "tls": True}',
        f'TLS_DOMAIN = "{tls_domain}"',
    ]
    if ad_tag:
        lines.append(f'AD_TAG = "{ad_tag}"')
    return "\n".join(lines) + "\n"
